# Generated by Django 4.0.5 on 2022-06-25 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yanprod', '0002_alter_shopunit_parentid_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='parentId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
